### DISCUSSION TITLE
Suggest adding a section about deployment, Also showing my AWS Amplify config.

### DISCUSSION THREAD

**Discussion by kingychiu** [histoire-dev/histoire#564] [Ideas]
I am hosting an Histoire instance successfully with the following AWS Amplify config. But I am not sure if is it enough, so I am suggesting adding documentation about this topic.

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run story:build
  artifacts:
    baseDirectory: .histoire/dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

A possible issue will be SSR, but it should not be my concern for a UI Components Library (hopefully).
